import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Brand configurations
  brands: defineTable({
    name: v.string(),
    slug: v.string(),
    url: v.optional(v.string()),

    voice: v.object({
      tone: v.string(),
      style: v.string(),
      rules: v.array(v.string()),
    }),

    visual: v.object({
      palette: v.object({
        primary: v.string(),
        secondary: v.string(),
        accent: v.string(),
        highlight: v.optional(v.string()),
      }),
      style: v.string(),
      mood: v.string(),
      avoid: v.array(v.string()),
      imageDirection: v.optional(v.object({
        subjects: v.optional(v.array(v.string())),
        technique: v.optional(v.array(v.string())),
        emotions: v.optional(v.array(v.string())),
        sceneTemplates: v.optional(v.any()),
      })),
    }),

    platforms: v.object({
      twitter: v.optional(v.object({ maxChars: v.number(), hashtags: v.number() })),
      linkedin: v.optional(v.object({ maxChars: v.number(), hashtags: v.number() })),
      facebook: v.optional(v.object({ maxChars: v.number(), hashtags: v.number() })),
      instagram: v.optional(v.object({ maxChars: v.number(), hashtags: v.number() })),
      threads: v.optional(v.object({ maxChars: v.number(), hashtags: v.number() })),
      youtube: v.optional(v.object({ titleMaxChars: v.number(), descriptionMaxChars: v.number() })),
    }),

    handles: v.optional(v.object({
      twitter: v.optional(v.string()),
      linkedin: v.optional(v.string()),
      facebook: v.optional(v.string()),
      instagram: v.optional(v.string()),
      threads: v.optional(v.string()),
      youtube: v.optional(v.string()),
    })),

    topics: v.array(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]),

  // ══════════════════════════════════════════════════════════════
  // CONTENT POOL - Ideas generated by Researcher, awaiting selection
  // ══════════════════════════════════════════════════════════════
  contentPool: defineTable({
    brandId: v.id("brands"),

    // The content idea
    idea: v.object({
      topic: v.string(),           // Core topic/theme
      angle: v.string(),           // The unique angle/hook
      hook: v.optional(v.string()), // Opening hook for content
      context: v.optional(v.string()), // Why now? Trends, events, etc.
    }),

    // Researcher's assessment
    research: v.object({
      source: v.optional(v.string()),  // Where the idea came from
      relevance: v.number(),           // 1-10 brand relevance score
      timeliness: v.optional(v.string()), // Evergreen, trending, seasonal
      notes: v.optional(v.string()),
    }),

    // Pool status
    status: v.union(
      v.literal("new"),        // Just added to pool
      v.literal("selected"),   // Picked by Strategist
      v.literal("rejected"),   // Passed over
      v.literal("used")        // Already generated content
    ),

    // When selected, strategist adds:
    strategy: v.optional(v.object({
      platforms: v.array(v.string()),  // Which platforms to target
      timing: v.optional(v.string()),  // When to post
      position: v.optional(v.string()), // How it fits in content calendar
      priority: v.optional(v.number()),
    })),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_brand", ["brandId"])
    .index("by_status", ["status"])
    .index("by_brand_status", ["brandId", "status"]),

  // ══════════════════════════════════════════════════════════════
  // GENERATIONS - Content shaped by Creative Director
  // ══════════════════════════════════════════════════════════════
  generations: defineTable({
    brandId: v.id("brands"),
    poolItemId: v.optional(v.id("contentPool")), // Link to pool item

    topic: v.string(),

    // Creative Director's concept
    concept: v.object({
      description: v.string(),
      reasoning: v.optional(v.string()),
      imagePrompt: v.string(),
      // Track variety - what aesthetic choices were made
      aestheticChoices: v.optional(v.object({
        mood: v.optional(v.string()),
        technique: v.optional(v.string()),
        subject: v.optional(v.string()),
      })),
    }),

    // Generated image
    image: v.optional(v.object({
      url: v.string(),
      model: v.string(),
      prompt: v.string(),
    })),

    // Platform copy
    content: v.object({
      twitter: v.optional(v.object({ text: v.string(), hashtags: v.array(v.string()) })),
      linkedin: v.optional(v.object({ text: v.string(), hashtags: v.array(v.string()) })),
      facebook: v.optional(v.object({ text: v.string(), hashtags: v.array(v.string()) })),
      instagram: v.optional(v.object({ text: v.string(), hashtags: v.array(v.string()) })),
      threads: v.optional(v.object({ text: v.string(), hashtags: v.array(v.string()) })),
    }),

    status: v.union(
      v.literal("generating"),
      v.literal("review"),
      v.literal("approved"),
      v.literal("scheduled"),
      v.literal("published"),
      v.literal("failed")
    ),

    agentThreadId: v.optional(v.string()),
    scheduledFor: v.optional(v.number()),
    publishedAt: v.optional(v.number()),
    publishResults: v.optional(v.array(v.object({
      platform: v.string(),
      success: v.boolean(),
      postId: v.optional(v.string()),
      postUrl: v.optional(v.string()),
      error: v.optional(v.string()),
    }))),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_brand", ["brandId"])
    .index("by_status", ["status"])
    .index("by_scheduled", ["scheduledFor"]),

  // ══════════════════════════════════════════════════════════════
  // AESTHETIC HISTORY - Track choices for variety
  // ══════════════════════════════════════════════════════════════
  aestheticHistory: defineTable({
    brandId: v.id("brands"),
    generationId: v.id("generations"),

    // What choices were made
    choices: v.object({
      mood: v.optional(v.string()),      // e.g., "contemplative", "hopeful"
      technique: v.optional(v.string()), // e.g., "macro", "silhouette"
      subject: v.optional(v.string()),   // e.g., "hands", "window", "nature"
      colorTone: v.optional(v.string()), // e.g., "warm", "muted", "high contrast"
    }),

    createdAt: v.number(),
  })
    .index("by_brand", ["brandId"])
    .index("by_brand_recent", ["brandId", "createdAt"]),

  // ══════════════════════════════════════════════════════════════
  // INSPIRATION LIBRARY - Reference prompts for learning
  // ══════════════════════════════════════════════════════════════
  inspirations: defineTable({
    category: v.string(),
    aesthetic: v.string(),
    prompt: v.any(),
    notes: v.optional(v.string()),
    tags: v.array(v.string()),
    createdAt: v.number(),
  })
    .index("by_category", ["category"])
    .index("by_aesthetic", ["aesthetic"]),
});
